### ISSUE TITLE
GUI: Name of images

### ISSUE THREAD

**Issue by KitetsuK** [X-R-G-B/ZappyCulteur#40]
# FOOD:
![honey](https://github.com/X-R-G-B/ZappyCulteur/assets/91657273/3763b0fd-0241-4ac0-9f7f-ad0bc69ca963)

# LINEMATE:
![rocks](https://github.com/X-R-G-B/ZappyCulteur/assets/91657273/463cb2c3-4e47-425c-8fe9-20c2df6af3a0)

# DERAUMERE:
![flower](https://github.com/X-R-G-B/ZappyCulteur/assets/91657273/598e9532-88db-4717-b454-011ef0860e5f)

# SIBUR:
![rose](https://github.com/X-R-G-B/ZappyCulteur/assets/91657273/35f6af23-b21e-4c9d-a083-f780a1116097)

# MENDIANE:
![hibiscus](https://github.com/X-R-G-B/ZappyCulteur/assets/91657273/23754955-b090-41a6-b22b-935b80871066)

# PHIRAS:
![camellia](https://github.com/X-R-G-B/ZappyCulteur/assets/91657273/0bed9ff3-663c-4033-a262-861d1c877b1e)

# THYSTAME:
![dahlia](https://github.com/X-R-G-B/ZappyCulteur/assets/91657273/7505394d-ae49-40eb-bd05-f27fd4f5d618)

**Comment by Saverio976** [comment]
c'est bon, c'est mis sur le readme
